service: tourneyman

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

package:
  include:
    - src/**

functions:
  events:
    handler: src/handler.events
    events: 
      - http:
          path: events
          method: get
          authorizer:
            arn: ${env:USER_POOL_ARN}
      - http:
          path: events
          method: post
          authorizer:
            arn: ${env:USER_POOL_ARN}
